export const sellPosts = [
  {
    userID: "user123",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Vintage Leather Jacket",
    description: "Discover a timeless classic with this Vintage Leather Jacket. Crafted with premium materials and exquisite attention to detail, this jacket exudes sophistication and style. Elevate your wardrobe with this versatile piece, perfect for any occasion.",
    price: 99.99,
    size: "Medium",
    gender: "Unisex",
    quantity: 1,
    picUrl: "https://www.kcleatherco.com/cdn/shop/files/ford_3_2048x.jpg?v=1689931980",
    category: "Clothing",
    datePost: "2023-12-15"
  },
  {
    userID: "user456",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Bomber Jacket",
    description: "Embrace urban style with this sleek Bomber Jacket. Designed for both comfort and fashion, this jacket features a modern silhouette and durable construction. Make a statement with this must-have addition to your wardrobe.",
    price: 99.99,
    size: "L",
    gender: "Men",
    quantity: 3,
    picUrl: "https://cdn11.bigcommerce.com/s-98f3d/images/stencil/1280x1280/products/2284/28306/Cockpit_USA_R.A.F._Fighter_Weight_Sheepskin_Bomber_Jacket_Brown_USA_Made_closeup__57589.1677262836.jpg?c=2",
    category: "Clothing",
    datePost: "2023-12-14"
  },
  {
    userID: "user789",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Nike Air Jordan 1 Retro High OG",
    description: "Step into style with the iconic Nike Air Jordan 1 Retro High OG. Featuring premium materials and timeless design, these sneakers are a must-have for any sneaker enthusiast. Elevate your streetwear look with this classic silhouette.",
    price: 199.99,
    size: "US 10",
    gender: "Men",
    quantity: 2,
    picUrl: "https://cdn.sanity.io/images/d6wcctii/production/00dd287e3096175b29ccc439e3c99803453ab7ab-1070x760.jpg?w=1200&q=80&fit=clip&auto=format",
    category: "Shoes",
    datePost: "2023-12-13"
  }, 
  {
    userID: "user789",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Satin Dress",
    description: "This dress drapes effortlessly, flattering your silhouette with every movement. The smooth texture and lustrous sheen of satin elevate its allure, making it the perfect choice for special occasions or glamorous evenings out. With its classic yet modern design, this dress effortlessly transitions from cocktail parties to formal events, ensuring you stand out with understated glamour.",
    price: 199.99,
    size: "M",
    gender: "Women",
    quantity: 2,
    picUrl: "https://finesse.us/cdn/shop/products/3D-Dress-Front.jpg?v=1674914516&width=1426",
    category: "Clothing",
    datePost: "2023-12-13"
  },
  {
    userID: "user101112",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Vintage 98/99 David Beckham",
    description: "Relive football history with this Vintage 98/99 David Beckham jersey. Celebrate the golden era of football with this iconic piece of memorabilia. Perfect for collectors and fans alike, this jersey is a true testament to sporting greatness.",
    price: 179.99,
    size: "L",
    gender: "Male",
    quantity: 1,
    picUrl: "https://i.ebayimg.com/images/g/y44AAOSw3N5lO5BD/s-l1600.jpg",
    category: "Clothing",
    datePost: "2023-12-12"
  },
  {
    userID: "user131415",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Leather Handbag",
    description: "Elevate your accessory game with this luxurious Leather Handbag. Crafted from premium leather and designed with elegance in mind, this handbag is the epitome of sophistication. Perfect for the modern woman on the go.",
    price: 149.99,
    size: "N/A",
    gender: "Female",
    quantity: 4,
    picUrl: "https://cdn11.bigcommerce.com/s-uiywfsyvbe/images/stencil/1280x1280/products/2458/12409/leather-purse-dark-brown-bag-tumbled-saddleback__59270.1686249399.jpg?c=1",
    category: "Accessories",
    datePost: "2023-12-11"
  },
  {
    userID: "user2345",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Straight-Fit Jeans",
    description: "Upgrade your casual style effortlessly with these classic denim jeans. Meticulously crafted from high-quality denim fabric, these jeans boast both durability and comfort. With a timeless design and versatile appeal, they seamlessly complement any wardrobe.",
    price: 89.99,
    size: "6",
    gender: "Female",
    quantity: 2,
    picUrl: "https://static.e-stradivarius.net/5/photos4/2024/V/0/1/p/7343/202/702/7343202702_2_4_1.jpg?t=1689848347398&impolicy=stradivarius-itxmediumhigh&imwidth=480&imformat=chrome&imdensity=2.625",
    category: "Clothing",
    datePost: "2024-1-13"
  },
  {
    userID: "user9857",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Women's Sweatshirt.",
    description: "Cozy oversized fit sweatshirt. Add a causual lounge wear to your everyday fit.",
    price: 59.99,
    size: "S",
    gender: "Female",
    quantity: 4,
    picUrl: "https://m.media-amazon.com/images/I/61e4wK4SBiL._AC_UY1000_.jpg",
    category: "Clothing",
    datePost: "2024-1-4"
  },
  {
    userID: "user9637",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Men's Sweatshirt",
    description: "Its simple yet timeless design makes it easy to pair with your favorite jeans or joggers for a versatile and effortlessly cool look. Whether you're lounging at home or heading out for a casual hangout with friends, this sweatshirt is sure to keep you looking and feeling your best. Stay comfortable and stylish with this essential addition to your closet.",
    price: 59.99,
    size: "M",
    gender: "Male",
    quantity: 5,
    picUrl: "https://m.media-amazon.com/images/I/61CATBYYloL._AC_SL1500_.jpg",
    category: "Clothing",
    datePost: "2024-2-5"
  },
  {
    userID: "user99587",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Sunglasses",
    description: "Trendy shades, designed to add a touch of sophistication to any outfit. With sleek frames and stylish lenses, these sunglasses are the perfect accessory for both casual outings and upscale events.",
    price: 40.00,
    size: "One Size",
    gender: "Unisex",
    quantity: 5,
    picUrl: "https://target.scene7.com/is/image/Target/GUEST_73be79b1-bf94-4ddd-a3af-9cabef4ab071?wid=1200&hei=1200&qlt=80&fmt=webp",
    category: "Accessories",
    datePost: "2023-12-17"
  },
  {
    userID: "user99587",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Gold Hoops",
    description: "Trendy gold hoops, designed to add a touch of sophistication to any outfit. Very classic look.",
    price: 40.00,
    size: "One Size",
    gender: "Women",
    quantity: 4,
    picUrl: "https://image.brilliantearth.com/media/product_images/JB/BE3165-Y_top.jpg",
    category: "Accessories",
    datePost: "2023-12-21"
  },
  {
    userID: "user99587",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Watch",
    description: "Embrace the art of timekeeping with our unparalleled selection of watches, where every moment is an opportunity to showcase your impeccable taste and style.",
    price: 200.00,
    size: "One Size",
    gender: "Women",
    quantity: 3,
    picUrl: "https://larssonjennings.com/cdn/shop/products/Boyfriend_Mini_Elevate_Gold_Green_1296x.jpg?v=1697367250",
    category: "Accessories",
    datePost: "2024-1-15"
  },
  {
    userID: "user99587",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Watch",
    description: "Accessorize your wrist with timeless sophistication with our collection of exquisite watches.",
    price: 300.00,
    size: "One Size",
    gender: "Men",
    quantity: 2,
    picUrl: "https://www.movado.com/dw/image/v2/BDKZ_PRD/on/demandware.static/-/Sites-mgi-master/default/dw810e31db/images/products/3650124w_LRG_rgb_Web.png?sw=720&sh=800",
    category: "Accessories",
    datePost: "2024-1-25"
  },
  {
    userID: "user89687",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Heels",
    description: "Step into elegance and confidence with our stunning collection of women's heels. These heels are the perfect accessory item to your wardrobe to dress up or down.",
    price: 59.99,
    size: "7",
    gender: "Women",
    quantity: 4,
    picUrl: "https://michaelkors.scene7.com/is/image/MichaelKors/40F2HNMP2L-1716_1?$large$",
    category: "Shoes",
    datePost: "2024-2-1"
  },
  {
    userID: "user99587",
    userProfileURL: "https://www.marismith.com/wp-content/uploads/2014/07/facebook-profile-blank-face.jpeg",
    title: "Boots",
    description: "Elevate your footwear game and embrace the essence of rugged refinement with these pair of men's boots.",
    price: 99.99,
    size: "11",
    gender: "Men",
    quantity: 5,
    picUrl: "https://www.ariat.com/dw/image/v2/AAML_PRD/on/demandware.static/-/Sites-ARIAT/default/dw8667a4cf/images/warm/10031452_3-4_front_warm.jpg?sw=800&sh=800",
    category: "Shoes",
    datePost: "2024-1-11"
  }
];
